### ISSUE TITLE
Required keys from back end are not available in available keys from Signature Provider.

### ISSUE THREAD

**Issue by ovicko** [EOSIO/eosio-java-android-example-app#13]
![eos_android_error](https://user-images.githubusercontent.com/7508165/57930083-b9086d00-78bd-11e9-8422-aaea7c4ee028.png)

```
one.block.eosiojava.error.session.TransactionSignAndBroadCastError: one.block.eosiojava.error.session.TransactionCreateSignatureRequestRequiredKeysEmptyError: Required keys from back end are not available in available keys from Signature Provider.
2019-05-17 16:00:54.119 26984-27688/one.block.androidexampleapp W/System.err:     at one.block.eosiojava.session.TransactionProcessor.signAndBroadcast(TransactionProcessor.java:483)
2019-05-17 16:00:54.119 26984-27688/one.block.androidexampleapp W/System.err:     at one.block.androidexampleapp.TransactionTask.doInBackground(TransactionTask.java:143)
2019-05-17 16:00:54.119 26984-27688/one.block.androidexampleapp W/System.err:     at one.block.androidexampleapp.TransactionTask.doInBackground(TransactionTask.java:54)
2019-05-17 16:00:54.119 26984-27688/one.block.androidexampleapp W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:345)
2019-05-17 16:00:54.119 26984-27688/one.block.androidexampleapp W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2019-05-17 16:00:54.119 26984-27688/one.block.androidexampleapp W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:257)
2019-05-17 16:00:54.119 26984-27688/one.block.androidexampleapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
2019-05-17 16:00:54.119 26984-27688/one.block.androidexampleapp W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
2019-05-17 16:00:54.119 26984-27688/one.block.androidexampleapp W/System.err:     at java.lang.Thread.run(Thread.java:784)
2019-05-17 16:00:54.120 26984-27688/one.block.androidexampleapp W/System.err: Caused by: one.block.eosiojava.error.session.TransactionCreateSignatureRequestRequiredKeysEmptyError: Required keys from back end are not available in available keys from Signature Provider.
2019-05-17 16:00:54.120 26984-27688/one.block.androidexampleapp W/System.err:     at one.block.eosiojava.session.TransactionProcessor.createSignatureRequest(TransactionProcessor.java:635)
2019-05-17 16:00:54.120 26984-27688/one.block.androidexampleapp W/System.err:     at one.block.eosiojava.session.TransactionProcessor.signAndBroadcast(TransactionProcessor.java:481)
2019-05-17 16:00:54.120 26984-27688/one.block.androidexampleapp W/System.err: 	... 8 more
```

**Comment by brandonfancher** [comment]
@ovicko Thanks for the issue! We will investigate based on the keys and `eosio.properties` file you sent to us offline.

**Comment by ovicko** [comment]
Thanks for the follow-up @brandonfancher

**Comment by DanteNguyen1008** [comment]
@ovicko 
There's problem is about we are having 2 format for SECP256K1 public key: EOS and PUB_K1_ . Soft Key Signature Provider has a flag to choose which key format it use: `setReturnLegacyFormatForK1`. 
Because your public key in the chain is EOS format (Legacy format) so you have to set the flag to TRUE.
Where can you set it in the example app?
In the `MainActivity`:

private void executeTransaction(final String nodeUrl) {
    ....
    new TransactionTask(new TransactionTask.TransactionTaskCallback() {
    .....
    }).execute(nodeUrl, fromAccount, toAccount, privateKey, amount, memo, `Boolean.TRUE.toString()`);
}

Please try that and let us know.

**Comment by ovicko** [comment]
@DanteNguyen1008  it returns these errors
`Caused by: one.block.eosiojava.error.session.TransactionCreateSignatureRequestRpcError: Error happened on calling getRequiredKeys RPC call.
2019-05-19 17:56:03.875 31159-31497/one.block.androidexampleapp W/System.err:     at one.block.eosiojava.session.TransactionProcessor.createSignatureRequest(TransactionProcessor.java:641)
2019-05-19 17:56:03.875 31159-31497/one.block.androidexampleapp W/System.err:     at one.block.eosiojava.session.TransactionProcessor.signAndBroadcast(TransactionProcessor.java:481)`

`Caused by: one.block.eosiojava.error.rpcProvider.GetRequiredKeysRpcError: Error retrieving required keys.
2019-05-19 17:56:03.876 31159-31497/one.block.androidexampleapp W/System.err:     at one.block.eosiojavarpcprovider.implementations.EosioJavaRpcProviderImpl.getRequiredKeys(EosioJavaRpcProviderImpl.java:188)
2019-05-19 17:56:03.876 31159-31497/one.block.androidexampleapp W/System.err:     at one.block.eosiojava.session.TransactionProcessor.createSignatureRequest(TransactionProcessor.java:623)`

`Caused by: one.block.eosiojavarpcprovider.error.EosioJavaRpcProviderCallError: Bad status code: 401 (Unauthorized), returned from server. Additional error information: See further error information in RPCProviderError.
2019-05-19 17:56:03.876 31159-31497/one.block.androidexampleapp W/System.err:     at one.block.eosiojavarpcprovider.implementations.EosioJavaRpcProviderImpl.processCall(EosioJavaRpcProviderImpl.java:115)
2019-05-19 17:56:03.876 31159-31497/one.block.androidexampleapp W/System.err:     at one.block.eosiojavarpcprovider.implementations.EosioJavaRpcProviderImpl.getRequiredKeys(EosioJavaRpcProviderImpl.java:186)`

**Comment by ovicko** [comment]
There is 401 error in the last error

**Comment by ovicko** [comment]
![eos_android_error](https://user-images.githubusercontent.com/7508165/57984147-5fd93e80-7a61-11e9-8b41-8d01be92c14b.png)

**Comment by DanteNguyen1008** [comment]
@ovicko I am trying to reproduce your error but I can't so far. I see one problem with your input. Could you change your input from 10.0000 EOS to 10.0000 EOS. Backend support up to .xxxx EOS only.

**Comment by ovicko** [comment]
@DanteNguyen1008 i have changed the transfer amount to 10.0000 EOS, still same problem

**Comment by DanteNguyen1008** [comment]
@ovicko I checked your account and look like the private key you are using (I have the full key with its public key you sent to us) is not in your account. Could you check your account again? 
Your account is using one same key for both owner and active key and I sent transaction with that key successfully.

**Comment by ovicko** [comment]
Thanks, it now works
